/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyComponpent: typeof import('./src/components/MyComponpent.vue')['default']
    NDarkToggle: typeof import('./src/components/NDarkToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport-flip')['Starport']
    StarportCarrier: typeof import('vue-starport-flip')['StarportCarrier']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheImage: typeof import('./src/components/TheImage.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
  }
}
